# common
oauth:
  kakao:
    user-info-request-url: https://kapi.kakao.com/v2/user/me
spring:
  config:
    import: file:.env[.properties]
application:
  name: DongBaeb
jwt:
  access-expiration: 180000
---
# dev
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DEV_MYSQL_URL}
    username: ${DEV_MYSQL_USER_NAME}
    password: ${DEV_MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: none
server:
  port: 8080
jwt:
  secret-key: ${JWT_TOKEN_SECRET_KEY}
---
# local
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dongbaeb
    username: sa
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8081
jwt:
  secret-key: JSON_WEB_TOKEN_SECRET_KEY_FOR_LOCAL_PROFILE
