server:
  port: 8081
oauth:
  kakao:
    user-info-request-url: https://kapi.kakao.com/v2/user/me
spring:
  config:
    import: file:.env[.properties]
application:
  name: DongBaeb
jwt:
  secret-key: ${JWT_TOKEN_SECRET_KEY}
  access-expiration: 1800000
