name: pr-build

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: gradlew에 실행 권한 부여
        run: chmod +x gradlew

      - name: .env 파일 생성
        run: |
          echo "KAKAO_APP_KEY=${{ secrets.KAKAO_APP_KEY }}" > .env
          echo "KAKAO_REDIRECT_URL_LOCAL=${{ secrets.KAKAO_REDIRECT_URL_LOCAL }}$" >> .env
          echo "JWT_TOKEN_SECRET_KEY=${{ secrets.JWT_TOKEN_SECRET_KEY }}$" >> .env

      - name: 빌드 및 테스트
        run: ./gradlew build
